fix some bugs and add some changes

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -40,7 +40,6 @@ services:
     depends_on:
       - db
       - rabbit
-      - minio
     stdin_open: true
     tty: true
     logging:
@@ -52,43 +51,43 @@ services:
   #-----------------------------------------------
   # Minio local storage helper
   #-----------------------------------------------
-  minio:
-    image: minio/minio:RELEASE.2020-10-03T02-19-42Z
-    command: server /export
-    volumes:
-      - ./var/minio:/export
-    restart: unless-stopped
-    ports:
-      - $MINIO_PORT:9000
-    env_file: .env
-    healthcheck:
-      test: ["CMD", "nc", "-z", "minio", "9000"]
-      interval: 5s
-      retries: 5
-  createbuckets:
-    image: minio/mc
-    depends_on:
-      minio:
-        condition: service_healthy
-    env_file: .env
-    # volumes:
-    #   This volume is shared with `minio`, so `z` to share it
-    #   - ./var/minio:/export
-    entrypoint: >
-      /bin/sh -c "
-      set -x;
-      if [ -n \"$MINIO_ACCESS_KEY\" ] && [ -n \"$MINIO_SECRET_KEY\" ] && [ -n \"$MINIO_PORT\" ]; then
-        until /usr/bin/mc config host add minio_docker http://minio:$MINIO_PORT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY && break; do 
-          echo '...waiting...' && sleep 5; 
-        done;
-        /usr/bin/mc mb minio_docker/$AWS_STORAGE_BUCKET_NAME || echo 'Bucket $AWS_STORAGE_BUCKET_NAME already exists.';
-        /usr/bin/mc mb minio_docker/$AWS_STORAGE_PRIVATE_BUCKET_NAME || echo 'Bucket $AWS_STORAGE_PRIVATE_BUCKET_NAME already exists.';
-        /usr/bin/mc anonymous set download minio_docker/$AWS_STORAGE_BUCKET_NAME;
-      else
-        echo 'MINIO_ACCESS_KEY, MINIO_SECRET_KEY, or MINIO_PORT are not defined. Skipping buckets creation.';
-      fi;
-      exit 0;
-      "
+  # minio:
+  #   image: minio/minio:RELEASE.2020-10-03T02-19-42Z
+  #   command: server /export
+  #   volumes:
+  #     - ./var/minio:/export
+  #   restart: unless-stopped
+  #   ports:
+  #     - $MINIO_PORT:9000
+  #   env_file: .env
+  #   healthcheck:
+  #     test: ["CMD", "nc", "-z", "minio", "9000"]
+  #     interval: 5s
+  #     retries: 5
+  # createbuckets:
+  #   image: minio/mc
+  #   depends_on:
+  #     minio:
+  #       condition: service_healthy
+  #   env_file: .env
+  #   # volumes:
+  #   #   This volume is shared with `minio`, so `z` to share it
+  #   #   - ./var/minio:/export
+  #   entrypoint: >
+  #     /bin/sh -c "
+  #     set -x;
+  #     if [ -n \"$MINIO_ACCESS_KEY\" ] && [ -n \"$MINIO_SECRET_KEY\" ] && [ -n \"$MINIO_PORT\" ]; then
+  #       until /usr/bin/mc config host add minio_docker http://minio:$MINIO_PORT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY && break; do 
+  #         echo '...waiting...' && sleep 5; 
+  #       done;
+  #       /usr/bin/mc mb minio_docker/$AWS_STORAGE_BUCKET_NAME || echo 'Bucket $AWS_STORAGE_BUCKET_NAME already exists.';
+  #       /usr/bin/mc mb minio_docker/$AWS_STORAGE_PRIVATE_BUCKET_NAME || echo 'Bucket $AWS_STORAGE_PRIVATE_BUCKET_NAME already exists.';
+  #       /usr/bin/mc anonymous set download minio_docker/$AWS_STORAGE_BUCKET_NAME;
+  #     else
+  #       echo 'MINIO_ACCESS_KEY, MINIO_SECRET_KEY, or MINIO_PORT are not defined. Skipping buckets creation.';
+  #     fi;
+  #     exit 0;
+  #     "
 
   #-----------------------------------------------
   #   Local development helper, rebuilds RiotJS/Stylus on change
@@ -123,9 +122,7 @@ services:
       - ./backups:/app/backups
     restart: unless-stopped
     logging:
-      options:
-        max-size: "20m"
-        max-file: "5"
+      driver: none
 
   #-----------------------------------------------
   #   Rabbitmq & Flower monitoring tool
@@ -214,8 +211,11 @@ services:
           memory: 256M
 
   compute_worker:
-    command: bash -c "watchmedo auto-restart -p '*.py' --recursive -- celery -A compute_worker worker -l info -Q compute-worker -n compute-worker@%n"
+    command: bash -c "watchmedo auto-restart -p '*.py' --recursive -- celery -A compute_worker worker -l info -Q compute-worker -n compute-worker@%n --concurrency=2"
     working_dir: /app
+    deploy:
+      replicas: 4
+    restart: unless-stopped
     build:
       context: .
       dockerfile: Dockerfile.compute_worker
